# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NYPNI1I1KKXP0Sdmb1hrdI2FPP75IQw
"""

a,b=10,20
print(a+b)