# -*- coding: utf-8 -*-
"""square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwkyeMS-Y4k-xk_RB1vfj0raHcXmtmxM
"""

n=7
print(n*n)